# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSTemplateAPP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSTemplateAPP
  # ---------------------------- 基础三方库 ----------------------
  pod 'AFNetworking' # 网络
  pod 'JKCategories' # 分类
  pod 'CocoaLumberjack' # 日志
  pod 'SDWebImage' # 图库
  pod 'Masonry' # 布局
  pod 'MJRefresh' # 刷新
  pod 'MJExtension' # Model
  
  # ---------------------- 其他 --------------------------------
  pod 'UMengAnalytics' #友盟统计
  pod 'FMDB' # SQLite3
  
end
