# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSTemplateAPP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSTemplateAPP

  pod 'AFNetworking' 
  pod 'JKCategories' # 分类
  
  pod 'UMengAnalytics' #友盟统计
  
  pod 'CocoaLumberjack' # 日志
  
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'FMDB'
end
